### ISSUE TITLE
Data download link appears to be broken

### ISSUE THREAD

**Issue by yashdeo55** [OpenXAIProject/Preprocessed_IXI_Dataset#2]
The temporary link which you have shared appears to be broken. Please can it be fixed?

Thanks

**Comment by wltjr1007** [comment]
As of right now, seems like it's working fine. Could you check again?

If it is broken, what HTTP error code do you get?

**Comment by yashdeo55** [comment]
Hello , 
It seems it was a problem from my side as my browser was blocking some plugins preventing the files from being downloaded .
Im closing the issue now thanks :)

**Comment by jiangwenjie123** [comment]
Excuse me, what sequence was used to collect the data in this IXI data set, thank you！
